[theme]
primaryColor="#2E86C1"         # Μπλε έντονο
backgroundColor="#F8F9F9"      # Πολύ ανοιχτό γκρι/λευκό
secondaryBackgroundColor="#D6EAF8" 
textColor="#1B2631"            # Σκούρο γκρι-μπλε
font="sans serif"
